/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pitmaper;
import org.junit.jupiter.api.Test;
import java.nio.file.Files;
import java.nio.file.Paths;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test public void testBlackWhite() {
        Bitmap classUnderTest = new Bitmap("mario", "BlackWhite", "BlackWhite");
        assertTrue(Files.exists(Paths.get("./src/main/resources/BlackWhite.bmp")), "app should create a file named Copymario in the main resources file.");
    }
}
